version: '3.7'

services:
 web:
  build: ./backend
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - ./backend/:/backend/
  ports:
  - "8000:8000"
  depends_on:
  - db
 db:
  image: postgres:latest
  environment:
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
  volumes:
   - postgres_data:/var/lib/postgresql/data
 frontend:
  build: ./frontend
  command: npm run dev
  volumes:
   - .:/frontend
   - /frontend/node_modules
  ports:
   - "5000:5000"
  
volumes:
 node-modules:
 postgres_data:
